package com.komabjn.threeplayerchess.rendering;

import com.komabjn.threeplayerchess.rendering.api.ThreePlayerChessRenderer;

/**
 *
 * @author Komabjn
 */
public class ThreePlayerChessboardRendererFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThreePlayerChessboardRendererImpl
     */
    public ThreePlayerChessboardRendererFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        threePlayerChessboardRendererImpl1 = new com.komabjn.threeplayerchess.rendering.ThreePlayerChessboardRendererImpl();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 1400));
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(threePlayerChessboardRendererImpl1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.komabjn.threeplayerchess.rendering.ThreePlayerChessboardRendererImpl threePlayerChessboardRendererImpl1;
    // End of variables declaration//GEN-END:variables

    public ThreePlayerChessRenderer getRenderer(){
        return threePlayerChessboardRendererImpl1;
    }
}
